### PR TITLE
MNT Broken builds

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/659

~~Fixes https://github.com/emteknetnz/recipe-kitchen-sink/actions/runs/3956659553/jobs/6776121726#step:12:67~~

~~`Error: Call to a member function getMinLength() on null /home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/cwp/cwp-core/tests/PasswordStrengthTest.php:32`~~

Fixes https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/3990680546/jobs/6844617693#step:12:67
`... contains "<link href="http://www.example.org/item-a/" />".`

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Seems like we are papering over the problem here. Member should have a `PasswordValidator` defined out of the box.

Why do we need to hack one in just for this test?

**Comment by emteknetnz** [comment]
I don't know why this was required in CMS 5, presumably there's bleed over from a different unit test that un-sets the default PasswordValidator

I'm confident that this regression is unit-test only.

I can manually confirm on my local install that includes this PR along with the others in `PageController::init()` that `var_dump(Member::password_validator());` still returns the default PasswordValidator

`object(SilverStripe\Security\PasswordValidator)#215 (8) { ["minLength":protected]=> int(10) ["minScore":protected]=> int(3) ["testNames":protected]=> array(4) { [0]=> string(9) "lowercase" [1]=> string(9) "uppercase" [2]=> string(6) "digits" [3]=> string(11) "punctuation" } ["historicalPasswordCount":protected]=> int(6) ["extension_instances":protected]=> NULL ["beforeExtendCallbacks":protected]=> array(0) { } ["afterExtendCallbacks":protected]=> array(0) { } ["extra_method_registers":protected]=> array(0) { } } `

Which matches the MinLength and MinTestScore config in cwp-core security.yml:
```
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\PasswordValidator:
    properties:
      MinLength: 10
      MinTestScore: 3
      HistoricCount: 6
```

**Comment by maxime-rainville** [comment]
The test is passing on my my local CMS5 sink. 

I have this file in the root of my project: https://github.com/silverstripe/recipe-core/blob/5/app/_config.php

The comment in there clearly state that Robbie was expecting this bit of code would need to be removed for CMS 5.

If I comment out the content on the file, I get the same error I'm currently seeing in the failing build.

Looking at the composer install log from the failing build, it looks like some other `app/_config.php` got put in the root of the project: https://github.com/emteknetnz/recipe-kitchen-sink/actions/runs/3956659553/jobs/6776121726#step:9:820

My guess is that depending in what order your recipes are installed the build may or may not pass.

**Review by maxime-rainville — APPROVED** [review]
LGTM ... I take it that my concern about the `PasswordValidator` got addressed elsewhere?

**Pull request merged**
